global:
  scrape_interval: 15s # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus_container:9090"]
  - job_name: "mysql"
    static_configs:
      - targets: ["mysqld_exporter:9104"]
