services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # Persistent data storage
    networks:
      - grafana_monitoring

volumes:
  portainer_data:

networks:
  grafana_monitoring:
    external: true
